// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5QkaCG0O9x-c4yxrskMYM6iFX38OOcik',
    appId: '1:84341817161:web:f98d7c00525d1f00d5e498',
    messagingSenderId: '84341817161',
    projectId: 'registro-a9d09',
    authDomain: 'registro-a9d09.firebaseapp.com',
    storageBucket: 'registro-a9d09.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAORZObF3SlyOykSNbAAC6ReBU5d0LA5SE',
    appId: '1:84341817161:android:5d0bd869ff0e11b4d5e498',
    messagingSenderId: '84341817161',
    projectId: 'registro-a9d09',
    storageBucket: 'registro-a9d09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD50Qw7wFPE08MuzdPXwbHPitvrbBRuFqU',
    appId: '1:84341817161:ios:a317714b4b91da66d5e498',
    messagingSenderId: '84341817161',
    projectId: 'registro-a9d09',
    storageBucket: 'registro-a9d09.firebasestorage.app',
    iosBundleId: 'com.example.holaMundo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD50Qw7wFPE08MuzdPXwbHPitvrbBRuFqU',
    appId: '1:84341817161:ios:a317714b4b91da66d5e498',
    messagingSenderId: '84341817161',
    projectId: 'registro-a9d09',
    storageBucket: 'registro-a9d09.firebasestorage.app',
    iosBundleId: 'com.example.holaMundo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5QkaCG0O9x-c4yxrskMYM6iFX38OOcik',
    appId: '1:84341817161:web:29602729541c2be0d5e498',
    messagingSenderId: '84341817161',
    projectId: 'registro-a9d09',
    authDomain: 'registro-a9d09.firebaseapp.com',
    storageBucket: 'registro-a9d09.firebasestorage.app',
  );
}
